from __future__ import annotations

import json
from typing import Any


def build_agentic_completion_prompt(
    *,
    strategy: str,
    domain: str,
    seed_item: dict[str, Any],
    candidate_sample: dict[str, Any],
    model: str,
) -> str:
    compact_candidate = _compact_mapping(candidate_sample)
    compact_seed = _compact_mapping(seed_item)
    metadata = seed_item.get("metadata") if isinstance(seed_item.get("metadata"), dict) else {}
    if metadata.get("verifier") == "terminal_bench_harness":
        return _build_terminal_bench_completion_prompt(
            strategy=strategy,
            domain=domain,
            compact_candidate=compact_candidate,
            compact_seed=compact_seed,
            model=model,
        )
    return f"""Convert the candidate training example into one Syn Agentic Data record.

Return exactly one JSON object, no markdown.
Required top-level keys: question, rationale, final_answer, metadata.

Generation-before constraints:
- question must be self-contained.
- rationale must be executable Python using only standard-library modules.
- rationale must print the answer on its final line.
- final_answer must exactly match the final line printed by rationale.
- Keep rationale concise: prefer a short direct computation/check over long exhaustive test suites.
- For programming tasks, use at most 3 to 5 representative checks in rationale.
- Do not include markdown fences inside any JSON string.
- metadata must include license, source, domain, required_dependencies, name, contributor, date_created.
- metadata.required_dependencies must be [].
- metadata.synthetic_strategy must be "{strategy}".
- metadata.synthetic_from_domain must be "{domain}".
- metadata.augmentation_model must be "{model}".

Candidate generated by the existing DataArc {strategy} generator:
{json.dumps(compact_candidate, ensure_ascii=False, indent=2)}

Reference seed item for domain and style only:
{json.dumps(compact_seed, ensure_ascii=False, indent=2)}
"""


def _build_terminal_bench_completion_prompt(
    *,
    strategy: str,
    domain: str,
    compact_candidate: Any,
    compact_seed: Any,
    model: str,
) -> str:
    return f"""Convert the candidate training example into one Syn Agentic Data record for a terminal-bench-style task.

Return exactly one JSON object, no markdown.
Required top-level keys: question, rationale, final_answer, metadata.

Generation-before constraints:
- question must be self-contained and describe the environment-backed objective at a high level.
- rationale should summarize the terminal-agent procedure and verifier contract; do not include benchmark-private files.
- final_answer should be "passed" only when metadata.tool_observation.status is "passed".
- Do not include markdown fences inside any JSON string.
- Do not copy canaries, hidden tests, golden solutions, private benchmark files, or full benchmark statements.
- Prefer task path and environment variable references over raw benchmark contents.
- metadata must include license, source, domain, required_dependencies, name, contributor, date_created.
- metadata.verifier must be "terminal_bench_harness".
- metadata.tool_spec must define the terminal agent tool schema.
- metadata.tool_call must call that tool with agent "codex" and model "gpt-5.5".
- metadata.tool_observation must contain a sanitized verifier summary.
- metadata.synthetic_strategy must be "{strategy}".
- metadata.synthetic_from_domain must be "{domain}".
- metadata.augmentation_model must be "{model}".

Candidate generated by the existing DataArc {strategy} generator:
{json.dumps(compact_candidate, ensure_ascii=False, indent=2)}

Reference seed item for domain and style only:
{json.dumps(compact_seed, ensure_ascii=False, indent=2)}
"""


def build_repair_prompt(record: dict[str, Any]) -> str:
    compact_record = _compact_failed_record(record)
    return f"""A generated Syn Agentic Data record failed schema validation or execution. Fix it.

Return exactly one JSON object, no markdown.
Required top-level keys: question, rationale, final_answer, metadata.
The rationale must be executable Python using only standard-library modules.
The rationale must print the answer on its final line.
The final_answer must exactly match the final line printed by rationale.
Keep rationale concise: prefer a short direct computation/check over long exhaustive test suites.
For programming tasks, use at most 3 to 5 representative checks in rationale.
Do not include markdown fences inside any JSON string.
metadata.required_dependencies must be [].
You may replace the failed sample with a shorter self-contained equivalent in the same domain and strategy.

Compact failed record:
{json.dumps(compact_record, ensure_ascii=False, indent=2, default=str)}
"""


def _compact_failed_record(record: dict[str, Any]) -> dict[str, Any]:
    generated_item = record.get("generated_item")
    return {
        "domain": record.get("domain"),
        "strategy": record.get("strategy"),
        "candidate_sample": _compact_mapping(record.get("candidate_sample")),
        "generated_item": _compact_mapping(generated_item) if isinstance(generated_item, dict) else None,
        "parse_error": _shorten(record.get("parse_error")),
        "schema_errors": record.get("schema_errors"),
        "verification": _compact_mapping(record.get("verification")),
        "repair_records": _compact_repairs(record.get("repair_records")),
    }


def _compact_repairs(repairs: Any) -> list[dict[str, Any]]:
    if not isinstance(repairs, list):
        return []
    compacted = []
    for repair in repairs[-2:]:
        if isinstance(repair, dict):
            compacted.append(
                {
                    "attempt": repair.get("attempt"),
                    "parse_error": _shorten(repair.get("parse_error")),
                    "schema_errors": repair.get("schema_errors"),
                    "verification": _compact_mapping(repair.get("verification")),
                }
            )
    return compacted


def _compact_mapping(value: Any) -> Any:
    if isinstance(value, dict):
        return {key: _compact_mapping(inner) for key, inner in value.items()}
    if isinstance(value, list):
        return [_compact_mapping(item) for item in value[:8]]
    return _shorten(value)


def _shorten(value: Any, limit: int = 700) -> Any:
    if not isinstance(value, str):
        return value
    if len(value) <= limit:
        return value
    return value[:limit] + "\n...[truncated]..."
